volume up: key(volup)
volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
(volume | media) mute: key(mute)
[media | music] play next: key(next)
[media | music] play previous: key(prev)
(media | music) (play | pause): user.play_pause()
